# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e89265b3c4e526dbd1633347d62611b6aa108491ab973a59012cd34ae374f38929fc007a93505371c3fced6cb7ced9922b3661ffbc69a67d25402f1809321ab3

test:
  secret_key_base: 52fffdb3f736dea35ce162da544a5b611f5f4838bb58d15a7f7f99bec094a5a91366b13b058175cc3aa770c4a3e2b72c61874199b97847490eb120bd8db4ef63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
